name: build_db_project

on: { push, pull_request }

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: create dacpac
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "./CM.WeeklyTeamReport/src/CM.WeeklyTeamReport.Domain/CM.WeeklyTeamReport.Database/CM.WeeklyTeamReport.Database.sqlproj" /p:Configuration=Release
      - uses: actions/upload-artifact@v2
        with:
          name: DACPAC
          path: ${{ github.workspace }}\src\CM.WeeklyTeamReport.Domain\CM.WeeklyTeamReport.Database\bin\Release\
